spring:
  application:
    name: family-points-backend
  # 数据库配置
  datasource:
    url: jdbc:postgresql://47.122.6.12:5432/family_points
    username: postgres
    password: Wasd1234!
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

# 服务器配置
server:
  servlet:
    context-path: /api

# MyBatis Plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.familypoints.backend.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# JWT配置
jwt:
  secret: your_jwt_secret_key_here
  expiration: 3600000  # 1小时，单位毫秒

---
# 开发环境配置
spring:
  config:
    activate:
      on-profile: dev
  # 数据库配置
  datasource:
    url: jdbc:postgresql://47.122.6.12:5432/family_points
    username: postgres
    password: Wasd1234!
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  # 微信小程序配置
  weixin:
    miniapp:
      appid: your_appid_here
      secret: your_secret_here

# 服务器配置
server:
  port: 8081

# JWT配置
jwt:
  secret: your_jwt_secret_key_here
  expiration: 3600000  # 1小时，单位毫秒

# 日志配置
logging:
  level:
    root: INFO
    com.familypoints.backend: DEBUG

---
# 生产环境配置
spring:
  config:
    activate:
      on-profile: prod
  # 数据库配置
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/family_points}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  # 微信小程序配置
  weixin:
    miniapp:
      appid: ${WEIXIN_APPID:your_appid_here}
      secret: ${WEIXIN_SECRET:your_secret_here}

# 服务器配置
server:
  port: ${SERVER_PORT:8080}

# JWT配置
jwt:
  secret: ${JWT_SECRET:your_jwt_secret_key_here}
  expiration: ${JWT_EXPIRATION:3600000}  # 1小时，单位毫秒

# 日志配置
logging:
  level:
    root: WARN
    com.familypoints.backend: INFO